### ISSUE TITLE
get_length_scale should be able to converge for periodic patterns

### ISSUE THREAD

**Issue by lmenou** [zwicker-group/py-droplets#12]
Assuming a periodic scalar field, it appears that the function droplets.get_length_scale is not converging for large variations of the field. If the length is big enough the optimizing method used does not converge. One possible workaround could be to check the periodicity of the associated grid and repeat the field on a bigger scale, rendering a convergence possible.

A warning should be addressed if such a workaround is used only for periodic field.

**Comment by david-zwicker** [comment]
Could you please provide an working example showing the issue? You could create an example field using `ScalarField.from_expression`.

**Comment by lmenou** [comment]
Here is such an example for a 1D field

```
import pde

grid = pde.CartesianGrid(bounds=[[0, 70]], shape=250, periodic=True)
field = pde.ScalarField.from_expression(grid, "0.2 + 0.2*sin(2*pi/90*x)")

field.plot()
```
